#!/usr/bin/env node
/*
 * Builds dist/ — the files the public site needs and nothing else — and writes dist/_headers
 * (Cloudflare Pages) with a strict Content-Security-Policy: every page's single inline script is
 * allowed by its SHA-256 hash, so no 'unsafe-inline' is needed for scripts.
 *
 *   node tools/build.js
 *
 * Re-run after ANY change to an HTML page: the hashes are of the exact inline script bytes.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = path.resolve(__dirname, '..');
const out = path.join(root, 'dist');

/* Browser origins the pages may call with fetch(): the concierge Worker (workers.dev now, api.<domain> later) */
const CONNECT = [
  'https://launch1500-concierge.launch1500-concierge-worker.workers.dev',
  'https://api.launch1500.ae'
];

const FILES = ['index.html', '200.html', 'polish.css', 'assistant.css', 'assistant.js', 'assistant-core.js', 'local-links.js', '_redirects'];
const DIRS = ['demos', 'start', 'assets'];
const PAGES = ['index.html', '200.html', 'demos/aed-1500/index.html', 'demos/aed-3000/index.html', 'demos/aed-5000/index.html', 'start/index.html'];
/* Source artwork that the pages no longer load (WebP copies are served instead) */
const UNUSED_ASSETS = ['launch1500_master_banner.png'];

function skip(file) {
  const base = path.basename(file);
  if (base === '.DS_Store') return true;
  if (UNUSED_ASSETS.indexOf(base) !== -1) return true;
  const ext = path.extname(base).toLowerCase();
  if (ext === '.png' || ext === '.jpg' || ext === '.jpeg') {
    /* skip a raster original when a .webp sibling exists (…-ar.jpg/.png → …-ar.webp) */
    const webp = path.join(path.dirname(file), base.slice(0, -ext.length) + '.webp');
    if (fs.existsSync(webp)) return true;
  }
  return false;
}

function copy(from, to) {
  const stat = fs.statSync(from);
  if (stat.isDirectory()) {
    fs.mkdirSync(to, { recursive: true });
    for (const name of fs.readdirSync(from)) copy(path.join(from, name), path.join(to, name));
  } else if (!skip(from)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

function inlineScriptHashes(html) {
  const hashes = [];
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = re.exec(html))) {
    const attrs = match[1];
    if (/\bsrc\s*=/.test(attrs)) continue;
    const type = (/\btype\s*=\s*["']?([^"'\s>]+)/i.exec(attrs) || [])[1];
    if (type && !/^(text\/javascript|application\/javascript|module)$/i.test(type)) continue; /* data blocks never execute */
    hashes.push("'sha256-" + crypto.createHash('sha256').update(match[2], 'utf8').digest('base64') + "'");
  }
  return hashes;
}

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
for (const file of FILES) copy(path.join(root, file), path.join(out, file));
for (const dir of DIRS) copy(path.join(root, dir), path.join(out, dir));

const hashes = [];
for (const page of PAGES) {
  for (const hash of inlineScriptHashes(fs.readFileSync(path.join(out, page), 'utf8'))) {
    if (hashes.indexOf(hash) === -1) hashes.push(hash);
  }
}

const csp = [
  "default-src 'self'",
  "script-src 'self' " + hashes.join(' '),
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  "connect-src 'self' " + CONNECT.join(' '),
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
  'upgrade-insecure-requests'
].join('; ');

const headers = [
  '# Generated by tools/build.js — do not edit by hand.',
  '/*',
  '  Content-Security-Policy: ' + csp,
  '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
  '  X-Content-Type-Options: nosniff',
  '  X-Frame-Options: DENY',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=(), usb=(), browsing-topics=()',
  '  Cross-Origin-Opener-Policy: same-origin-allow-popups',
  '',
  '# Images are versioned by file name; scripts and styles revalidate hourly.',
  '/assets/*',
  '  Cache-Control: public, max-age=2592000, stale-while-revalidate=86400',
  '/*.css',
  '  Cache-Control: public, max-age=3600, stale-while-revalidate=86400',
  '/*.js',
  '  Cache-Control: public, max-age=3600, stale-while-revalidate=86400',
  ''
].join('\n');
fs.writeFileSync(path.join(out, '_headers'), headers);

fs.mkdirSync(path.join(out, '.well-known'), { recursive: true });
fs.writeFileSync(path.join(out, '.well-known', 'security.txt'), [
  'Contact: https://wa.me/971503923733',
  'Preferred-Languages: en, ar',
  'Canonical: https://launch1500.ae/.well-known/security.txt',
  'Expires: 2027-09-30T00:00:00.000Z',
  ''
].join('\n'));

let bytes = 0, count = 0;
(function walk(dir) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name);
    const s = fs.statSync(p);
    if (s.isDirectory()) walk(p); else { bytes += s.size; count += 1; }
  }
})(out);
console.log('dist/: ' + count + ' files, ' + (bytes / 1024 / 1024).toFixed(2) + ' MB');
console.log('inline script hashes: ' + hashes.length);
if ((csp.length + 27) > 2000) console.warn('WARNING: CSP header line exceeds the 2000-character _headers limit');
